### ISSUE TITLE
Feature to do something when story is paused

### ISSUE THREAD

**Issue by prissyazzahra** [hannadrehman/stories-react#17]
Hi,

I am currently using this library to make Instagram stories, and I am planning to add animations using Lottie. However when I pause the story, I couldn't find a way to update the state during this time as there are no props that allow me to do it (something like onStoriesStart, onStoryChange, or onStoriesEnd). I would like to suggest a feature where developers are able to do something (i.e. update state, call function, etc) when a story is paused.

I tried to do detect long presses using refs and onMouseDown out of a few other things, but I still couldn't update the state. I would also appreciate if there are any suggestions on what I should do to update the state on pause.

Thanks and have a great day.

**Comment by hannadrehman** [comment]
what state are you planing to update ? do u want to resume the story after it was paused ? 
also if could share some snippets that will help

**Comment by prissyazzahra** [comment]
Hi, thanks for the reply. I'm planning to pass an isPaused prop when a story is paused. Here's a snippet of one of the stories.

```
const slide2 = () => {
    return (
      <div
        style={{
          backgroundImage: `url(${Image3})`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundPosition: "center center",
          minHeight: "calc(100vh - 56px)",
          textAlign: "center",
          padding: "28px 17px",
        }}
      >
        <Animation animationData={handball} isPaused={ /* any way to pass the isPaused prop of the story to this element? */ } />
      </div>
    );
  };
```
So when the story isPaused, the Animation element can be paused too. Is there any way to do this?

**Comment by estyhutami** [comment]
Hi! Thank you for the awesome library. I am experiencing a similar case but with the need for loading bar adjustment too. is it also possible if we can have a callback for onPause?

**Comment by estyhutami** [comment]
the isPaused props exposed is nice too, with the same functionality as react-insta-stories library

**Comment by hannadrehman** [comment]
@prissyazzahra let me try to put down your requirements 
1. we should be able to pause a story
2. we should be able to get a paused state 
3. we should be able to resume the story which updates the state. 
4. global onPause callback

in your particular i example i am thinking to add `isPaused` state in the story component and avoid the global callback. 


```jsx

function slide2({onPause, onResume, story, isPaused}) {
  // isPaused will have paused state
    return (
      <div
        style={{
          backgroundImage: `url(${Image3})`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundPosition: "center center",
          minHeight: "calc(100vh - 56px)",
          textAlign: "center",
          padding: "28px 17px",
        }}
      >
       <button onClick={onPause}>pause this story</button>
       <button onClick={onResume}>resume  paused story</button>
        <Animation
          animationData={handball} 
          isPaused={isPaused /* or maybe directly get an isPaused prop from the story itself? */}
        />
      </div>
    );
  };

/* ... */

<Stories
  defaultDuration={5000}
  stories={stories} // stories contains Story2 as component story
  height={"100vh"}
/>

```

we could totally avoid global onPause callback though.

**Comment by hannadrehman** [comment]
> Hi! Thank you for the awesome library. I am experiencing a similar case but with the need for loading bar adjustment too. is it also possible if we can have a callback for onPause?
> 
> Probably like this: `onPause: (isPaused) =>`

what use-case do u have for global on pause?. when i built this library i deliberately left the this out. 
one use-case i can think of is to add analytics on all pauses user did .

**Comment by prissyazzahra** [comment]
Ok I think the isPaused props is sufficient, thank you 😄

**Comment by hannadrehman** [comment]
> Hi! Thank you for the awesome library. I am experiencing a similar case but with the need for loading bar adjustment too. is it also possible if we can have a callback for onPause?
 can u pls create a separate issue with your requirements.
