### ISSUE TITLE
give a way to style the white background by providing `containerClassName` prop

### ISSUE THREAD

**Issue by deadcoder0904** [hannadrehman/stories-react#19]
**Is your feature request related to a problem? Please describe.**
currently, i can't style the background using anything other than `white`

**Describe the solution you'd like**
i always style in dark mode & would love dark background using a prop like `containerClassname` as i style through tailwind

**Describe alternatives you've considered**
passing a `containerClassname` prop

**Additional context**
<img width="467" alt="Screenshot 2022-02-23 at 7 29 31 PM" src="https://user-images.githubusercontent.com/16436270/155334001-03f6fba4-6370-4a6a-acba-f2905a60de17.png">

i tried `className` as `h-screen p-0 m-0` on the `Story` & got the above result but still some `white` remains. see my code:

```tsx
import WhatsappStories from 'stories-react'

interface IStory {
	title: string
	body: string
}

interface IStories {
	stories: IStory[]
}

const Story = ({ title, body }: IStory) => {
	return (
		<div className="dark:bg-primary h-screen p-0 m-0">
			<h3>{title}</h3>
			<p>{body}</p>
		</div>
	)
}

export const Stories = ({ stories }: IStories) => {
	const allStories = stories.map((s) => ({
		type: 'component',
		duration: 9000,
		component: () => <Story title={s.title} body={s.body} />,
	}))

	return (
		<WhatsappStories
			width="400px"
			height="600px"
			stories={allStories}
			className="dark:bg-indigo-700"
		/>
	)
}
```

would love to style it with a simple `containerClassName` prop & for the 2 `div`'s above `WhatsappStories` & a `className` prop for the `WhatsappStories` as well so the `bg-indigo-700` works :)

**Comment by hannadrehman** [comment]
this is a good usecase. i will add some classnames which allows to update all containers.
