### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by quedicesebas** [hannadrehman/stories-react#30]
I made a PR but I need help with it #29

**Comment by hannadrehman** [comment]
i was not able to pull ur branch. i have created a new pr for the same. https://github.com/hannadrehman/stories-react/pull/32
u can close ur pr. and i will merge this one.

**Comment by hannadrehman** [comment]
Updated library deps. you can preview the sandbox here https://codesandbox.io/s/competent-cohen-yvefy3?file=/src/_app.js

**Comment by quedicesebas** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1771574/222998862-6353d7ae-6c75-4982-ba2b-2033e6a2c6d6.png">

**Comment by hannadrehman** [comment]
can u create a reproducible codesandbox for this ? i will check there whats happening

**Comment by quedicesebas** [comment]
Checked ✅.
