### ISSUE TITLE
Add optional Loop props to optionally re-run the story from the start

### ISSUE THREAD

**Issue by redlpd** [hannadrehman/stories-react#42]
Add `Loop` props

```
<Stories loop />
```

Will re-run the story from the start if set to `true` when the slides reaches the last item

**Comment by redlpd** [comment]
Add `Loop` props

```
<Stories loop />
```

Will re-run the story from the start if set to `true` when the slides reaches the end

**Comment by hannadrehman** [comment]
Hi @redlpd  this is a nice suggestions. i am not able to find time right now to work on it. would love to have a PR for this
